version: "3.8"

services:
  postgres:
    image: postgres:15.5
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: healthinsurance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak-server
    command: start-dev
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"

volumes:
  postgres_data: